- apt_repository:
    repo: ppa:fkrull/deadsnakes
    state: present

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes


- name: Install python 3.6
  apt:
    name: "{{item}}"
    force_apt_get: true
  become: true
  become_user: root
  with_items:
    - python3.6

- name: ensure important python apt packages are installed
  apt: name={{item}}
  become: true
  become_user: root
  with_items:
    - python-virtualenv
    - python-dev
    - python3-dev
    - build-essential
    - libsasl2-dev
    - libssl-dev
    - libffi-dev

