- hosts: aws
  become: true
  gather_facts: false
  vars:
    app_name: "weather_app"
    app_path: "chapter1/src"
    executable: "version2.py"
    repo: "https://github.com/Sureya/data-engineering-101.git"

    api_key: "{{ lookup('env','API_KEY') }}"
    database_nme: "{{ lookup('env','DB_NAME') }}"
    db_user: "{{ lookup('env','DB_USER') }}"
    db_password: "{{ lookup('env','DB_PWD') }}"
    host: "{{ lookup('env','DB_HOST') }}"

  roles:
    - python-app

  pre_tasks:
    - include: roles/common_tasks/ubuntu16_python2.yml
      static: yes

  post_tasks:
    - name: "Schedule job to run at 11:00 everyday" # 24 hour time format
      cron:
        name: "python-app-11"
        minute: "0"
        hour: "11"
        job: "cd {{app_dir}} ;  {{venv_dir}}/bin/python3 {{executable}} --api_key={{api_key}} --database={{database_nme}} --user={{db_user}} --password={{db_password}} --host={{host}}"
