# Prepares python virtual environment and install requirements

- name: Delete old virtual environment if exists
  file:
    state: absent
    path: "{{venv_dir}}/"

- name: create virtualenv directory if it does not already exist
  file: path={{ venv_dir }} state=directory

- name: Check if path to requirements.txt exists
  stat: path={{ requirements_path }}
  register: check_requirements_path

- name: install dependencies into a new virtualenv
  when: check_requirements_path.stat.exists
  pip: requirements={{ requirements_path }}
       virtualenv="{{venv_dir}}/" virtualenv_python=python3

